import {readFile,writeFile} from "node:fs/promises";
import {APPROVED_SCRIPT_FILE as source,extractApprovedVoiceOver} from "../src/contracts/content-contract.js";
import {FinancePlanSchema,compileFinancePlan,transitionFor} from "../src/contracts/finance-motion.js";
import {resolveHeroCaptions,editorialKaraokeAss,editorialCaptionWords} from "../src/contracts/hero-captions.js";
import {ScriptSchema} from "../src/render/script-schema.js";

const day=Number(process.argv[2]);if(![4,5,6,7].includes(day))throw new Error("Day 4–7 required");
const out=`output/benchmarks/day-${day}-v12-differentactually`;
const read=async(p:string)=>JSON.parse(await readFile(`${out}/${p}`,"utf8"));
const script=ScriptSchema.parse(await read("script.json")),transcript=await read("transcript.json");
const approved=extractApprovedVoiceOver(await readFile(source,"utf8"),day);
const ref=(scene:number,sourceSpan:string)=>({source,sceneId:`scene-${scene}`,sourceSpan});
const box=(x:number,y:number,w:number,h:number)=>({x,y,w,h});
const txt=(id:string,scene:number,label:string,b:ReturnType<typeof box>,fontSize=72,initial=false,role="SECTION_MARKER")=>({id,kind:"text",box:b,copy:{...ref(scene,label),text:label.toUpperCase()},role,fontSize,size:"heading",initial});
const node=(id:string,icon:string,b:ReturnType<typeof box>,initial=false)=>({id,kind:"node",icon,box:b,initial,entityGroup:"objects"});
const metric=(id:string,b:ReturnType<typeof box>)=>({id,kind:"metric",datumId:id,box:b,role:"DATA_LABEL"});
const ev=(id:string,scene:number,phrase:string,action:string,targets:string[],relation="progression",pose?:object)=>({id,trigger:ref(scene,phrase),action,targets,relation,transition:transitionFor(relation),rationale:`The source phrase ${phrase} changes only its related retained semantic object.`,...(pose?{pose}:{})});
const seq=(id:string,scenes:number[],elements:unknown[],motionEvents:unknown[],visualModel="decision-flow")=>({id,sceneIds:scenes.map(n=>`scene-${n}`),visualModel,semanticRationale:"Connected source-supported states preserve object identity and reveal each new idea at its spoken boundary.",entryRelation:"new-topic",entryTransition:"crossfade",elements,motionEvents});
const heading=box(130,380,820,260),left=box(150,800,300,240),right=box(630,800,300,240);
let data:any[]=[],sequences:any[]=[],items:any[]=[];
if(day===4)sequences=[
 seq("emotion-wiring",[1,2],[txt("emotion",1,"Emotional spending",heading,100,true,"HERO"),node("wallet","wallet",left,true),node("question","question",right)],[ev("question",1,"willpower problem","reveal",["question"]),ev("wiring",2,"wiring problem","focus",["wallet"],"same-object",{opacity:.55})]),
 seq("feeling-relief",[3,4],[txt("feelings",3,"stressed, bored, or exhausted",heading,76,true,"HERO"),node("order","order",left),node("coffee","coffee",right),txt("minutes",3,"about ten minutes",box(130,1120,820,160),66)],[ev("minutes",3,"about ten minutes","reveal",["minutes"]),ev("order",4,"online order","reveal",["order"]),ev("coffee",4,"coffee run","reveal",["coffee"])]),
 seq("relief-bill",[5,6],[txt("biology",5,"That's biology",heading,100,true,"HERO"),node("purchase","order",left,true),node("bill","wallet",right),txt("short",6,"the relief is short",box(130,1120,820,170),72)],[ev("bill",6,"the relief is short","reveal",["short"]),ev("relief-recedes",6,"and the bill isn't","focus",["purchase"],"same-object",{opacity:.25}),ev("bill-remains",6,"the bill isn't","reveal",["bill"])]),
 seq("checkout-feeling",[7,8,9],[txt("question",7,"what am I feeling right now",heading,80),node("checkout","order",box(410,760,260,200),true),txt("tired",8,"tired",box(130,1110,240,160),64),txt("bored",8,"bored",box(420,1110,240,160),64),txt("anxious",8,"anxious",box(710,1110,240,160),64)],[ev("ask",7,"what am I feeling right now","reveal",["question"]),ev("tired",8,"tired","reveal",["tired"]),ev("bored",8,"bored","reveal",["bored"]),ev("anxious",8,"anxious","reveal",["anxious"]),ev("urge-passes",9,"urge pass","focus",["checkout"],"same-object",{opacity:.25})]),
 seq("honest-question",[10],[txt("discipline",10,"You don't need more discipline",heading,86,true,"HERO"),node("question","question",box(400,820,280,260),true)],[ev("discipline",10,"more discipline","focus",["question"],"same-object")]),
];
if(day===5){
 for(const [id,scene,phrase,value] of [["guess-three",3,"three",3],["guess-four",3,"four",4],["actual-eight",4,"eight",8],["actual-twelve",4,"twelve",12]] as const){data.push({...ref(scene,phrase),id,sourceType:"script-literal",value,unit:"count",display:String(value),qualifier:"exact"});items.push({id,sceneId:`scene-${scene}`,spokenPhrase:phrase,canonicalText:phrase,displayText:String(value),context:scene===3?"three or four":"eight to twelve",target:"stat.value",template:"stat-hero"});}
 sequences=[
 seq("guess-statement",[1,2],[txt("guess",1,"guess how many",heading,108,true,"HERO"),node("question","question",left,true),node("statement","wallet",right)],[ev("paying",1,"currently paying for","focus",["question"],"same-object"),ev("statement",2,"bank statement","reveal",["statement"])]),
 seq("range-comparison",[3,4,5],[txt("guess",3,"Most people guess",box(130,290,820,130),74,true,"HERO"),metric("guess-three",box(210,460,200,220)),txt("or",3,"or",box(470,490,140,150),60),metric("guess-four",box(670,460,200,220)),txt("actually",4,"Most people actually have",box(130,750,820,100),58),metric("actual-eight",box(210,910,200,220)),txt("to",4,"to",box(470,930,140,150),60),metric("actual-twelve",box(670,910,200,220)),node("cloud","cloud",box(130,1180,220,160)),node("trial","app",box(430,1180,220,160)),node("fitness","fitness",box(730,1180,220,160))],[ev("three",3,"three","reveal",["guess-three"],"major-metric"),ev("or",3,"or","reveal",["or"]),ev("four",3,"four","reveal",["guess-four"],"major-metric"),ev("actually",4,"Most people actually have","reveal",["actually"]),ev("eight",4,"eight","reveal",["actual-eight"],"major-metric"),ev("to",4,"to","reveal",["to"]),ev("twelve",4,"twelve","reveal",["actual-twelve"],"major-metric"),ev("cloud",5,"cloud storage","reveal",["cloud"]),ev("trial",5,"forgotten trial","reveal",["trial"]),ev("fitness",5,"fitness app","reveal",["fitness"])],"metric-reveal"),
 seq("charge-attention",[6,7],[txt("forgettable",6,"designed to be forgettable",heading,78,true,"HERO"),node("charge","wallet",left,true),node("recipient","app",right)],[ev("forgotten",6,"not an accident","focus",["charge"],"same-object",{opacity:.35}),ev("recipient",7,"income for someone else","reveal",["recipient"])]),
 seq("monthly-review",[8,9],[txt("monthly",8,"once a month",heading,108,true,"HERO"),node("calendar","calendar",left,true),node("statement","wallet",right),txt("seconds",8,"ten seconds each",box(130,1130,820,160),72)],[ev("statement",8,"open your statement","reveal",["statement"]),ev("seconds",8,"ten seconds each","reveal",["seconds"]),ev("look",9,"just to see it","focus",["statement"],"same-object")]),
 seq("actually-look",[10],[txt("extreme",10,"You don't have to be extreme",heading,80,true,"HERO"),node("question","question",box(400,820,280,260),true)],[ev("extreme",10,"extreme","focus",["question"],"same-object")]),
 ];
}
if(day===6){data=[{...ref(10,"five dollars"),id:"weekly-five",sourceType:"script-literal",value:5,unit:"USD",display:"$5",qualifier:"exact"}];items=[{id:"weekly-five",sceneId:"scene-10",spokenPhrase:"five dollars",canonicalText:"five dollars a week",displayText:"$5",context:"a week",target:"stat.value",template:"stat-hero"}];sequences=[
 seq("scarcity-question",[1,2],[txt("saving",1,"saving money feels impossible",heading,86,true,"HERO"),node("wallet","wallet",left,true),node("question","question",right)],[ev("math",1,"math problem","reveal",["question"]),ev("scarcity",2,"scarcity mindset","focus",["wallet"],"same-object",{opacity:.5})]),
 seq("tight-wallet",[3,4,5],[txt("tight",3,"money has felt tight",heading,96,true,"HERO"),node("wallet","wallet",box(350,800,380,250),true),txt("unsafe",5,"saving feel unsafe",box(130,1140,820,150),80)],[ev("past",3,"years ago","focus",["wallet"],"same-object",{opacity:.6}),ev("dollar",4,"every dollar","focus",["wallet"],"same-object",{opacity:1}),ev("unsafe",5,"saving feel unsafe","reveal",["unsafe"])]),
 seq("knowing-feeling",[6,7,8],[txt("advice",6,"just spend less",heading,100,true,"HERO"),node("question","question",box(400,760,280,220),true),txt("fear",7,"the actual fear",box(130,1090,820,150),88),txt("safe",8,"saving doesn't FEEL safe",heading,86)],[ev("advice-fades",6,"doesn't work","focus",["question"],"same-object",{opacity:.45}),ev("fear",7,"the actual fear","reveal",["fear"]),ev("clear-advice",8,"it's not that","hide",["advice"],"same-object"),ev("safe",8,"saving doesn't FEEL safe","reveal",["safe"])]),
 seq("weekly-safekeeping",[9,10,11],[txt("small",9,"so small",heading,124,true,"HERO"),node("wallet","wallet",box(150,800,260,210),true),metric("weekly-five",box(600,780,330,240)),txt("week",10,"a week",box(600,1120,330,150),74),txt("savings",11,"savings",box(130,1120,330,150),70)],[ev("small",9,"almost pointless","focus",["wallet"],"same-object",{opacity:.65}),ev("five",10,"five dollars","reveal",["weekly-five"],"major-metric"),ev("week",10,"a week","reveal",["week"]),ev("savings",11,"into savings","reveal",["savings"]),ev("retained",11,"doesn't mean losing it","focus",["wallet"],"same-object",{opacity:1})],"metric-reveal"),
 ];}
if(day===7)sequences=[
 seq("five-category-recap",[1,2,3,4],[txt("week",1,"This week",box(130,240,820,110),84,true,"HERO"),node("recurring","app",box(130,410,180,150)),txt("subscription",1,"subscription creep",box(350,410,600,150),62),node("lifestyle","car",box(130,605,180,150)),txt("lifestyle-label",1,"lifestyle creep",box(350,605,600,150),64),node("math","wallet",box(130,800,180,150)),txt("math-label",1,"girl math",box(350,800,600,150),64),node("emotion","order",box(130,995,180,150)),txt("emotion-label",1,"emotional spending",box(350,995,600,150),60),node("saving","question",box(130,1190,180,150)),txt("saving-label",1,"saving feels impossible",box(350,1190,600,150),52)],[ev("recurring",1,"subscription creep","reveal",["recurring","subscription"]),ev("lifestyle",1,"lifestyle creep","reveal",["lifestyle","lifestyle-label"]),ev("math",1,"girl math","reveal",["math","math-label"]),ev("emotion",1,"emotional spending","reveal",["emotion","emotion-label"]),ev("saving",1,"saving feels impossible","reveal",["saving","saving-label"]),ev("five",2,"Five different habits","focus",["recurring","lifestyle","math","emotion","saving"],"same-object"),ev("common",3,"One thing in common","focus",["recurring","lifestyle","math","emotion","saving"],"same-object",{opacity:.65}),ev("noticing",4,"not noticing","focus",["recurring","lifestyle","math","emotion","saving"],"same-object",{opacity:1})]),
 seq("honest-question-recap",[5,6],[txt("spreadsheet",5,"a spreadsheet",heading,108,true,"HERO"),node("question","question",box(400,800,280,240),true),txt("honest",6,"one honest question",box(130,1130,820,170),70)],[ev("spreadsheet",5,"to fix","focus",["question"],"same-object"),ev("honest",6,"one honest question","reveal",["honest"])]),
 seq("single-choice",[7,8,9,10],[txt("one",7,"pick just ONE",heading,120,true,"HERO"),node("selection","question",box(400,800,280,240),true),txt("clearly",10,"one habit you finally see clearly",box(130,1110,820,190),65)],[ev("today",7,"today","focus",["selection"],"same-object"),ev("just-one",8,"Just one","focus",["selection"],"same-object"),ev("no-overhaul",9,"full budget overhaul","focus",["selection"],"same-object",{opacity:.6}),ev("clearly",10,"one habit you finally see clearly","reveal",["clearly"]),ev("focus",10,"see clearly","focus",["selection"],"same-object",{opacity:1})]),
];
// Include the narrated outro in the retained semantic state. This selects the
// existing editorial outro, then clears the state at the final WordBoundary.
const lastSequence=sequences.at(-1)!;
const outro=script.scenes.at(-1)!;
lastSequence.sceneIds.push(outro.id);
if(day===4)lastSequence.motionEvents.push(ev("honest-question-payoff",11,"one honest question","focus",["question"],"same-object",{opacity:1}));
if(day===5)lastSequence.motionEvents.push(ev("look-payoff",11,"actually look","focus",["question"],"same-object",{opacity:1}));
const lastWord=transcript.scenes.at(-1).words.at(-1).text;
lastSequence.motionEvents.push({...ev("outro-clear",Number(outro.id.replace("scene-","")),lastWord,"hide",lastSequence.elements.map((e:any)=>e.id),"same-object"),anchor:"end"});
const plan=FinancePlanSchema.parse({version:"1.2",day,source,referencePolicy:"VISUAL_REFERENCE_ONLY",editorial:true,data,sequences});
const resolved=compileFinancePlan(plan,script,transcript,approved);
// Range operators remain in the accessible sentence as well as the diagram.
// Suppressing only OR/TO would leave the misleading caption THREE FOUR.
const specs=plan.sequences.flatMap(s=>s.elements.filter(e=>e.copy&&["HERO","SECTION_MARKER"].includes(e.role??"")&&!(day===5&&["or","to"].includes(e.id))).map(e=>({...ref(Number(e.copy!.sceneId.replace("scene-","")),e.copy!.sourceSpan),sequenceId:s.id,elementIds:[e.id]})));
const captions=resolveHeroCaptions(specs,resolved,transcript);
for(const [f,v] of Object.entries({"data_visualizations.json":plan,"resolved-finance-plan.json":resolved,"hero-captions.json":specs,"resolved-hero-captions.json":captions,"number_highlights.json":{version:"1.0",day,source,items},"caption-coverage.json":editorialCaptionWords(transcript,captions)}))await writeFile(`${out}/${f}`,JSON.stringify(v,null,2));
await writeFile(`${out}/subtitles.ass`,editorialKaraokeAss(transcript,captions,script));
console.log(`Day ${day} compiled`,resolved.sequences.map(s=>({id:s.id,start:s.startSec,end:s.endSec})));
